from sqlalchemy import String,Text,ForeignKey,Enum,Integer,Float,JSON,Boolean
from sqlalchemy.orm import Mapped,mapped_column
from app.database import Base
from app.models.base import TimestampMixin
from app.utils.enums import InterviewMode,InterviewType,Difficulty,InterviewStatus,ExperienceLevel
class InterviewQuestion(Base,TimestampMixin):
 __tablename__='interview_questions'; id:Mapped[int]=mapped_column(primary_key=True); question_text:Mapped[str]=mapped_column(Text); role_id:Mapped[int|None]=mapped_column(ForeignKey('career_roles.id',ondelete='SET NULL')); category:Mapped[str]=mapped_column(String(80)); difficulty:Mapped[Difficulty]=mapped_column(Enum(Difficulty)); interview_type:Mapped[InterviewType]=mapped_column(Enum(InterviewType)); expected_key_points:Mapped[list]=mapped_column(JSON,default=list); expected_keywords:Mapped[list]=mapped_column(JSON,default=list); sample_answer:Mapped[str|None]=mapped_column(Text); is_active:Mapped[bool]=mapped_column(Boolean,default=True)
class InterviewSession(Base,TimestampMixin):
 __tablename__='interview_sessions'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); role_id:Mapped[int|None]=mapped_column(ForeignKey('career_roles.id',ondelete='SET NULL')); resume_id:Mapped[int|None]=mapped_column(ForeignKey('resumes.id',ondelete='SET NULL')); interview_type:Mapped[InterviewType]=mapped_column(Enum(InterviewType)); mode:Mapped[InterviewMode]=mapped_column(Enum(InterviewMode)); experience_level:Mapped[ExperienceLevel]=mapped_column(Enum(ExperienceLevel)); difficulty:Mapped[Difficulty]=mapped_column(Enum(Difficulty)); duration_minutes:Mapped[int]=mapped_column(Integer,default=20); requested_questions:Mapped[int]=mapped_column(Integer,default=5); preferred_language:Mapped[str]=mapped_column(String(20),default='en'); job_description:Mapped[str|None]=mapped_column(Text); status:Mapped[InterviewStatus]=mapped_column(Enum(InterviewStatus),default=InterviewStatus.CREATED,index=True); current_order:Mapped[int]=mapped_column(Integer,default=0)
class SessionQuestion(Base):
 __tablename__='session_questions'; id:Mapped[int]=mapped_column(primary_key=True); session_id:Mapped[int]=mapped_column(ForeignKey('interview_sessions.id',ondelete='CASCADE'),index=True); question_id:Mapped[int]=mapped_column(ForeignKey('interview_questions.id')); order_no:Mapped[int]=mapped_column(Integer); skipped:Mapped[bool]=mapped_column(Boolean,default=False)
class InterviewAnswer(Base,TimestampMixin):
 __tablename__='interview_answers'; id:Mapped[int]=mapped_column(primary_key=True); session_question_id:Mapped[int]=mapped_column(ForeignKey('session_questions.id',ondelete='CASCADE'),unique=True); answer_text:Mapped[str|None]=mapped_column(Text); media_key:Mapped[str|None]=mapped_column(String(255)); transcript:Mapped[str|None]=mapped_column(Text); duration_seconds:Mapped[float|None]=mapped_column(Float)
class AnswerEvaluation(Base,TimestampMixin):
 __tablename__='answer_evaluations'; id:Mapped[int]=mapped_column(primary_key=True); answer_id:Mapped[int]=mapped_column(ForeignKey('interview_answers.id',ondelete='CASCADE'),unique=True); final_score:Mapped[float]=mapped_column(Float); category_scores:Mapped[dict]=mapped_column(JSON); raw_signals:Mapped[dict]=mapped_column(JSON); strengths:Mapped[list]=mapped_column(JSON); weaknesses:Mapped[list]=mapped_column(JSON); feedback:Mapped[str]=mapped_column(Text); improved_answer:Mapped[str|None]=mapped_column(Text); scoring_version:Mapped[str]=mapped_column(String(40),default='interview-v1')
